### ISSUE TITLE
llama2-7b 모델 학습시 OOM 에러 발생

### ISSUE THREAD

**Issue by DONGRYEOLLEE1** [jwj7140/Gugugo#2]
안녕하세요 좋은 모델 공개해주셔서 너무 감사드립니다.

공개해주신 학습코드를 바탕으로 llama2-ko-7b 모델을 만들고 있는데 OOM에러가 자꾸 발생해 문의드립니다.

다음은 제 패키지 버전과 소스코드입니다.

accelerate               0.25.0.dev0
bitsandbytes             0.41.1
peft                     0.7.1.dev0
torch                    2.1.1
transformers             4.36.0.dev0
GPU: 3090 (24GB)
OS: Ubuntu 22.04
python: 3.10.12

```python
data = load_dataset("squarelike/sharegpt_deepl_ko_translation")
def makedata(x):
    if (x['num'] % 2 == 0):
        return {'text': f"### 한국어: {x['korean']}</끝>\n### 영어: {x['english']}</끝>"}
    else:
        return {'text': f"### 영어: {x['english']}</끝>\n### 한국어: {x['korean']}</끝>"}

data = data.map(makedata)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
model = AutoModelForCausalLM.from_pretrained("beomi/llama-2-ko-7b", quantization_config = bnb_config, device_map = 'auto', trust_remote_code = True)
tokenizer = AutoTokenizer.from_pretrained("beomi/llama-2-ko-7b")

data = data.map(lambda x: tokenizer(x['text']), batched = True)

config = LoraConfig(
    r = 8,
    lora_alpha = 32,
    target_modules = ["q_proj", "v_proj"],
    lora_dropout = 0.05,
    bias = "none",
    task_type = "CAUSAL_LM"
)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, config)

tokenizer.pad_token = tokenizer.eos_token

trainer = Trainer(
    model = model,
    train_dataset = data['train'],
    args = TrainingArguments(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 2,
        fp16 = True,
        output_dir = "results/llama2-ko-7b-translation",
        save_total_limit = 2,
        logging_steps = 100,
        save_steps = 100,
        num_train_epochs = 1,
        learning_rate = 3e-4,
        optim = "adamw_torch",
        # lr_scheduler_type = "cosine",
        # resume_from_checkpoint = True,
    ),
    data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False)
)

model.config.use_cache = False

trainer.train()

```

위 코드로 학습 진행했을때, 207스텝에서 OOM에러가 발생하였습니다.

**Comment by jwj7140** [comment]
인터넷에 공개된 [squarelike/sharegpt_deepl_ko_translation](https://huggingface.co/datasets/squarelike/sharegpt_deepl_ko_translation) 데이터셋은 최대 1300자 분량의 데이터인 [translation_data_sharegpt.json](https://huggingface.co/datasets/squarelike/sharegpt_deepl_ko_translation/blob/main/translation_data_sharegpt_v19.json)과 최대 7000자 분량의 데이터인 [translation_data_sharegpt_long.json](https://huggingface.co/datasets/squarelike/sharegpt_deepl_ko_translation/blob/main/translation_data_sharegpt_long_v7.json)으로 나누어져 있습니다.

학습하는 데이터가 길수록 VRAM을 더 차지하기 때문에, OOM 발생시 짧은 데이터로 학습하는 것이 도움이 될 수 있습니다.
```python
data = load_dataset("squarelike/sharegpt_deepl_ko_translation", data_files=["translation_data_sharegpt_v19.json"])
```
참고로 말씀드리자면 [gugugo-koen-7b-v1.1](https://huggingface.co/squarelike/Gugugo-koen-7B-V1.1)은 모든 데이터를 학습하기 위해 **A6000 48GB**에서 학습되었습니다.
