### ISSUE TITLE
webUI 데모의 모델 파일 저장 경로 문제

### ISSUE THREAD

**Issue by Tococo838** [jwj7140/Gugugo#3]
먼저 멋진 프로젝트를 만들어 주심에 감사드립니다!
번역 품질이 좋아서 너무도 유용하게 잘 쓰고 있습니다.

다름이 아니라, 해당 깃을 클론하여 webUI 데모를 실행할 경우 모델 파일을 다운받고 시작하는데요.
임시 파일로 취급되는 모양인지 오랜 시간이 지난 후 어떤 이유로든 파일이 유실되어 다시 받아야 하는 경우가 있었습니다.

- 모델 파일이 다운로드 되는 경로가 어떻게 되나요?
- 모델 파일의 위치를 다른 경로로 특별히 지정할 수 있을까요?

**Comment by jwj7140** [comment]
huggingface에서 다운로드 받는 모델 파일들은 기본적으론 윈도우의 경우 ```C:\Users\username\.cache\huggingface```, 리눅스의 경우 ```/home/username/.cache/huggingface```에 저장됩니다.

이는 .from_pretrained 함수의 ```cache_dir``` 옵션으로 변경이 가능합니다.
```
AutoTokenizer..from_pretrained(model_id, cache_dir="./model")
model = AutoModelForCausalLM.from_pretrained(model_id, cache_dir="./model")
```
